import React from 'react';

export default function HelpModal({ isOpen, onClose }: { isOpen: boolean, onClose: () => void }) {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      <div className="absolute inset-0 bg-black/80 backdrop-blur-sm" onClick={onClose}></div>
      <div className="relative bg-[#050D0C] border border-[#5DBF7E]/40 rounded-2xl w-full max-w-3xl max-h-[80vh] overflow-y-auto shadow-[0_0_50px_rgba(93,191,126,0.15)] flex flex-col">
        
        {/* Header */}
        <div className="sticky top-0 bg-[#050D0C] border-b border-[#5DBF7E]/20 p-6 flex justify-between items-center z-10">
          <h2 className="text-2xl font-black tracking-[0.2em] text-[var(--color-primary)] drop-shadow-[0_0_10px_rgba(93,191,126,0.4)]">
            HOW TO PLAY: YIELD TACTICS
          </h2>
          <button onClick={onClose} className="text-white/50 hover:text-white font-bold text-xl">✕</button>
        </div>

        {/* Content */}
        <div className="p-8 text-white/80 font-sans space-y-8">
          <section>
            <h3 className="text-xl font-bold text-white mb-3 tracking-widest border-l-4 border-[var(--color-primary)] pl-3">1. ENTER MATCH (100% LOSSLESS)</h3>
            <p className="leading-relaxed">
              Connect your wallet and deposit an equal stake into the DuelManager. 
              <br/><br/>
              <span className="text-[var(--color-primary)] font-bold">LOSSLESS GUARANTEE:</span> The principal you stake is <em>never</em> put at risk. You are only fighting for the accumulated DeFi yield generated by the smart contracts during the match.
            </p>
          </section>

          <section>
            <h3 className="text-xl font-bold text-white mb-3 tracking-widest border-l-4 border-[#FF4D6D] pl-3">2. ALLOCATE RESOURCES</h3>
            <p className="leading-relaxed">
              In each round, you must allocate 100% of your power across three core mechanics:
            </p>
            <ul className="mt-4 space-y-3 pl-4">
              <li className="flex gap-3"><span className="text-[#FF4D6D] font-black w-24">ATTACK</span> Drain a % of your opponent's yield gain.</li>
              <li className="flex gap-3"><span className="text-[#4DA3FF] font-black w-24">DEFEND</span> Block incoming attacks from your opponent.</li>
              <li className="flex gap-3"><span className="text-[var(--color-invest)] font-black w-24">INVEST</span> Compound and multiply your own treasury.</li>
            </ul>
            <p className="mt-4 text-sm text-white/50 italic">Moves are secretly committed on-chain so your opponent cannot front-run you.</p>
          </section>

          <section>
            <h3 className="text-xl font-bold text-white mb-3 tracking-widest border-l-4 border-[#4DA3FF] pl-3">3. COMBAT RESOLUTION</h3>
            <p className="leading-relaxed">
              Once both players commit, the round resolves via Rock-Paper-Scissors logic:
            </p>
            <div className="bg-black/50 p-4 rounded-xl mt-3 font-mono text-sm space-y-2 border border-white/10">
              <div><span className="text-[#FF4D6D]">Attack</span> vs <span className="text-[#4DA3FF]">Defend</span> = Blocked (Attack wasted)</div>
              <div><span className="text-[#FF4D6D]">Attack</span> vs <span className="text-[var(--color-invest)]">Invest</span> = Direct Hit (Drain opponent yield)</div>
              <div><span className="text-[var(--color-invest)]">Invest</span> vs <span className="text-[var(--color-invest)]">Invest</span> = Both players grow cleanly</div>
            </div>
          </section>

          <section>
            <h3 className="text-xl font-bold text-white mb-3 tracking-widest border-l-4 border-[var(--color-warning)] pl-3">4. DAILY SPLIT POOL</h3>
            <p className="leading-relaxed">
              Alongside 1v1 duels, there is a global <strong>Daily Split Pool</strong>. You can lock capital in the pool and commit a master strategy. At the end of the day, the top 10% most efficient allocators automatically share the global generated yield!
            </p>
          </section>

          <section>
            <h3 className="text-xl font-bold text-white mb-3 tracking-widest border-l-4 border-purple-400 pl-3">5. AUTONOMOUS BOT NETWORK</h3>
            <p className="leading-relaxed">
              This game is actively populated by an autonomous bot driver operating as a state machine. It constantly creates games, commits strategies, reveals moves, and injects liquidity into the Daily Pool. This guarantees constant opponent availability and live volume!
            </p>
          </section>
        </div>

        {/* Footer */}
        <div className="sticky bottom-0 bg-[#050D0C] border-t border-[#5DBF7E]/20 p-6 flex justify-end z-10">
          <button onClick={onClose} className="px-8 py-3 bg-[var(--color-primary)] text-black font-black tracking-widest rounded-xl hover:shadow-[0_0_20px_rgba(93,191,126,0.6)] transition-all">
            ACKNOWLEDGE
          </button>
        </div>

      </div>
    </div>
  );
}
