/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface AutoSplitRouterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getSplitRules"
      | "owner"
      | "renounceOwnership"
      | "routePayment"
      | "setSplitRules"
      | "setVaultAdapter"
      | "totalTransactions"
      | "totalVolume"
      | "transferOwnership"
      | "userSplits"
      | "vaultAdapters"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "PaymentRouted"
      | "SplitRuleUpdated"
      | "VaultAdapterUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getSplitRules",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "routePayment",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setSplitRules",
    values: [AddressLike[], BigNumberish[], boolean[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setVaultAdapter",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "totalTransactions",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalVolume",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userSplits",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "vaultAdapters",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getSplitRules",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "routePayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSplitRules",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVaultAdapter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalTransactions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalVolume",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userSplits", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "vaultAdapters",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentRoutedEvent {
  export type InputTuple = [
    sender: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    recipients: AddressLike[],
    amounts: BigNumberish[]
  ];
  export type OutputTuple = [
    sender: string,
    token: string,
    amount: bigint,
    recipients: string[],
    amounts: bigint[]
  ];
  export interface OutputObject {
    sender: string;
    token: string;
    amount: bigint;
    recipients: string[];
    amounts: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SplitRuleUpdatedEvent {
  export type InputTuple = [
    user: AddressLike,
    recipients: AddressLike[],
    basisPoints: BigNumberish[],
    isVault: boolean[]
  ];
  export type OutputTuple = [
    user: string,
    recipients: string[],
    basisPoints: bigint[],
    isVault: boolean[]
  ];
  export interface OutputObject {
    user: string;
    recipients: string[];
    basisPoints: bigint[];
    isVault: boolean[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultAdapterUpdatedEvent {
  export type InputTuple = [vault: AddressLike, enabled: boolean];
  export type OutputTuple = [vault: string, enabled: boolean];
  export interface OutputObject {
    vault: string;
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AutoSplitRouter extends BaseContract {
  connect(runner?: ContractRunner | null): AutoSplitRouter;
  waitForDeployment(): Promise<this>;

  interface: AutoSplitRouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getSplitRules: TypedContractMethod<
    [user: AddressLike],
    [
      [string[], bigint[], boolean[]] & {
        recipients: string[];
        basisPoints: bigint[];
        isVault: boolean[];
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  routePayment: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "payable"
  >;

  setSplitRules: TypedContractMethod<
    [
      recipients: AddressLike[],
      basisPoints: BigNumberish[],
      isVault: boolean[]
    ],
    [void],
    "nonpayable"
  >;

  setVaultAdapter: TypedContractMethod<
    [vault: AddressLike, enabled: boolean],
    [void],
    "nonpayable"
  >;

  totalTransactions: TypedContractMethod<[], [bigint], "view">;

  totalVolume: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  userSplits: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, bigint, boolean] & {
        recipient: string;
        basisPoints: bigint;
        isVault: boolean;
      }
    ],
    "view"
  >;

  vaultAdapters: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getSplitRules"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [string[], bigint[], boolean[]] & {
        recipients: string[];
        basisPoints: bigint[];
        isVault: boolean[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "routePayment"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "setSplitRules"
  ): TypedContractMethod<
    [
      recipients: AddressLike[],
      basisPoints: BigNumberish[],
      isVault: boolean[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setVaultAdapter"
  ): TypedContractMethod<
    [vault: AddressLike, enabled: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalTransactions"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalVolume"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userSplits"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, bigint, boolean] & {
        recipient: string;
        basisPoints: bigint;
        isVault: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "vaultAdapters"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PaymentRouted"
  ): TypedContractEvent<
    PaymentRoutedEvent.InputTuple,
    PaymentRoutedEvent.OutputTuple,
    PaymentRoutedEvent.OutputObject
  >;
  getEvent(
    key: "SplitRuleUpdated"
  ): TypedContractEvent<
    SplitRuleUpdatedEvent.InputTuple,
    SplitRuleUpdatedEvent.OutputTuple,
    SplitRuleUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "VaultAdapterUpdated"
  ): TypedContractEvent<
    VaultAdapterUpdatedEvent.InputTuple,
    VaultAdapterUpdatedEvent.OutputTuple,
    VaultAdapterUpdatedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PaymentRouted(address,address,uint256,address[],uint256[])": TypedContractEvent<
      PaymentRoutedEvent.InputTuple,
      PaymentRoutedEvent.OutputTuple,
      PaymentRoutedEvent.OutputObject
    >;
    PaymentRouted: TypedContractEvent<
      PaymentRoutedEvent.InputTuple,
      PaymentRoutedEvent.OutputTuple,
      PaymentRoutedEvent.OutputObject
    >;

    "SplitRuleUpdated(address,address[],uint256[],bool[])": TypedContractEvent<
      SplitRuleUpdatedEvent.InputTuple,
      SplitRuleUpdatedEvent.OutputTuple,
      SplitRuleUpdatedEvent.OutputObject
    >;
    SplitRuleUpdated: TypedContractEvent<
      SplitRuleUpdatedEvent.InputTuple,
      SplitRuleUpdatedEvent.OutputTuple,
      SplitRuleUpdatedEvent.OutputObject
    >;

    "VaultAdapterUpdated(address,bool)": TypedContractEvent<
      VaultAdapterUpdatedEvent.InputTuple,
      VaultAdapterUpdatedEvent.OutputTuple,
      VaultAdapterUpdatedEvent.OutputObject
    >;
    VaultAdapterUpdated: TypedContractEvent<
      VaultAdapterUpdatedEvent.InputTuple,
      VaultAdapterUpdatedEvent.OutputTuple,
      VaultAdapterUpdatedEvent.OutputObject
    >;
  };
}
